{% set version = "1.2.0" %}

package:
  name: libdicom
  version: {{ version }}

source:
  url: https://github.com/ImagingDataCommons/libdicom/releases/download/v{{ version }}/libdicom-{{ version }}.tar.xz
  sha256: 3b8c05ceb6bf667fed997f23b476dd32c3dc6380eee1998185c211d86a7b4918

build:
  number: 1
  run_exports:
    # just a guess
    - {{ pin_subpackage('libdicom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - meson
    - pkg-config

test:
  commands:
    - test -f $PREFIX/lib/libdicom${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\dicom-1.dll exit 1   # [win]

about:
  home: https://github.com/ImagingDataCommons/libdicom
  summary: 'C library for reading DICOM files'
  description: |
    libdicom is a C library and a set of command-line tools for reading DICOM WSI files.
    It is free (MIT licensed), fast, cross-platform, uses little memory, has no
    dependencies, includes API documentation, and is easy to use from languages like Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://libdicom.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/ImagingDataCommons/libdicom

extra:
  recipe-maintainers:
    - kaczmarj
