{% set version = "1.0.5" %}

package:
  name: libdicom
  version: {{ version }}

source:
  url: https://github.com/ImagingDataCommons/libdicom/releases/download/v{{ version }}/libdicom-{{ version }}.tar.xz
  sha256: 3b88f267b58009005bc1182d8bd0c4a3218013ce202da722e5e8c9867c6f94f4

build:
  number: 1
  skip: True  # [win]
  run_exports:
    # just a guess
    - {{ pin_subpackage('libdicom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - pkg-config

test:
  commands:
    - test -f $PREFIX/lib/libdicom${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\libdicom.dll exit 1   # [win]

about:
  home: https://github.com/ImagingDataCommons/libdicom
  summary: 'C library for reading DICOM files'
  description: |
    libdicom is a C library and a set of command-line tools for reading DICOM WSI files.
    It is free (MIT licensed), fast, cross-platform, uses little memory, has no
    dependencies, includes API documentation, and is easy to use from languages like Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://libdicom.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/ImagingDataCommons/libdicom

extra:
  recipe-maintainers:
    - kaczmarj
